// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Character struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Subtitle    string `json:"subtitle"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	Language    string `json:"language"`
	Greeting    string `json:"greeting"`
}

type GetCharacterByIdReq struct {
	Id int64 `path:"id,optional"`
}

type GetCharacterByIdResp struct {
	Character
}

type GetCharactersReq struct {
}

type GetCharactersResp struct {
	List []*Character `json:"list"`
}
