// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Character struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Subtitle    string `json:"subtitle"`
	Description string `json:"description"`
	Tags        string `json:"tags"`
	Language    string `json:"language"`
	Greeting    string `json:"greeting"`
}

type ChatHistory struct {
	Role    string `json:"role"`
	Content string `json:"content"`
	Created int64  `json:"created"`
}

type CreateChatReq struct {
	CharacterId int64  `json:"characterId"`
	Content     string `json:"content"`
}

type CreateChatResp struct {
	Content string `json:"content"`
}

type GetCharacterByIdReq struct {
	Id int64 `path:"id"`
}

type GetCharacterByIdResp struct {
	Character
}

type GetCharactersReq struct {
}

type GetCharactersResp struct {
	List []*Character `json:"list"`
}

type GetChatHistoryReq struct {
	Id int64 `path:"id"`
}

type GetChatHistoryResp struct {
	Histories []*ChatHistory `json:"histories"`
}

type TruncateChatHistoryReq struct {
	Id int64 `path:"id"`
}

type TruncateChatHistoryResp struct {
}
