services:
  mysql:
    image: mysql:8.0
    container_name: ai-chat-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - ai-chat
    volumes:
      - ./data/mysql/data:/var/lib/mysql

networks:
  ai-chat: