// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	voiceFieldNames          = builder.RawFieldNames(&Voice{})
	voiceRows                = strings.Join(voiceFieldNames, ",")
	voiceRowsExpectAutoSet   = strings.Join(stringx.Remove(voiceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	voiceRowsWithPlaceHolder = strings.Join(stringx.Remove(voiceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	voiceModel interface {
		Insert(ctx context.Context, data *Voice) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Voice, error)
		Update(ctx context.Context, data *Voice) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVoiceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Voice struct {
		Id          int64  `db:"id"`
		Type        string `db:"type"`
		Description string `db:"description"`
	}
)

func newVoiceModel(conn sqlx.SqlConn) *defaultVoiceModel {
	return &defaultVoiceModel{
		conn:  conn,
		table: "`voice`",
	}
}

func (m *defaultVoiceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVoiceModel) FindOne(ctx context.Context, id int64) (*Voice, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", voiceRows, m.table)
	var resp Voice
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVoiceModel) Insert(ctx context.Context, data *Voice) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, voiceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Type, data.Description)
	return ret, err
}

func (m *defaultVoiceModel) Update(ctx context.Context, data *Voice) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, voiceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Type, data.Description, data.Id)
	return err
}

func (m *defaultVoiceModel) tableName() string {
	return m.table
}
