// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	characters "backend/internal/handler/characters"
	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/character/:id",
				Handler: characters.GetCharacterByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/characters",
				Handler: characters.GetCharactersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
