// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	characters "backend/internal/handler/characters"
	chat "backend/internal/handler/chat"
	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/character/:id",
				Handler: characters.GetCharacterByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/characters",
				Handler: characters.GetCharactersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: chat.CreateChatHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat/:id",
				Handler: chat.GetChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/chat/:id",
				Handler: chat.TruncateChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat/voice",
				Handler: chat.GetVoiceWaveHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
